# Generated by Django 4.0 on 2021-12-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='gender',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question2',
            field=models.CharField(max_length=200),
        ),
    ]
